### ISSUE TITLE
Iscsid and multipathd don't get configured on first install

### ISSUE THREAD

**Issue by Logibox** [hpe-storage/common-host-libs#71]
See https://github.com/hpe-storage/common-host-libs/blob/0956514067237e2cf75c94957ec21a92d75d67ec/tunelinux/iscsi.go#L407
and https://github.com/hpe-storage/common-host-libs/blob/0956514067237e2cf75c94957ec21a92d75d67ec/tunelinux/multipath.go#L328

```go
...
	// Start service
	err = linux.ServiceCommand(iscsi, "start")
	if err != nil {
		return err
	}

	err = SetIscsiRecommendations()
	if err != nil {
		return err
	}
...
```

In the `iscsi` code above the configuration file is edited *after* the service is already started with no reload, so the `iscsid` process will continue to use to old settings until the process is restarted.

**Comment by shivamerla** [comment]
@Logibox thanks for reporting this. This is resolved.
